### PR TITLE
Remove "geographic" from description

### LINKED ISSUE #50: Md_Scope change
There is a needed change to the Md_Scope codelist as indicated in isotc211: https://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode
and confirmed by ISO 19115-1, 2014 amendment as follows:

Drop "geographic" from definition:
-  dataset: information applies to a _geographic_ dataset
-  dataset: information applies to a dataset

### PR DESCRIPTION
**Pull request by jwaspin**
Closes #50 

# Changes

* Removed "geographic" from the description of a dataset

### CODE REVIEW

**Comment by dwalt** [comment]
@jwaspin Need to know where mdTools is hosted in order to test it, currently known container address is not updated.

**Comment by dwalt** [comment]
Does not appear it was removed when reviewing mdcodes on 8050

**Comment by hmaier-fws** [comment]
Made slight edit to change definition from "information applies to **a dataset**" to "...**the dataset**". The iso_scope.yml aligns with the definitions provided in https://standards.iso.org/iso/19115/-3/mcc/1.0/codelists.xml.

**Review by hmaier-fws — APPROVED** [review]
ISO definitions match those defined in https://standards.iso.org/iso/19115/-3/mcc/1.0/codelists.xml

**Pull request merged**
